New antd version causing issues
I'm getting this error on `http://localhost:5678/create-organization/`

```
Unhandled Runtime Error TypeError: Object is not a function or its return value is not iterable
```